name: Deploy to Firebase

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: crisis-line-web/package-lock.json
        
    - name: Install dependencies
      run: |
        cd crisis-line-web
        npm ci
        
    - name: Build React app
      run: |
        cd crisis-line-web
        npm run build
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools@13.0.0
        
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: crisislineapp
        channelId: live
